compiler_path = "clang++"
compiler_std = "c++20"
headers_path = [ "lib" ]
sources_path = [ "install.cc" ]
output_name = "install.o"
compiler_flags = [ "-fPIC" ]
cpp_macros = [ "__INSTALL__" ]
run_after_build = false
