compiler_path = "clang++"
compiler_std = "c++20"
headers_path = [ "../lib", "../lib/libocl/dev/", "/opt/homebrew/Cellar/boost/1.89.0/include" ]
sources_path = [ "steps.cc" ]
output_name = "steps.o"
compiler_flags = [ "-fPIC" ]
cpp_macros = [ "__NE_STEPS__" ]
run_after_build = false
