name: Ne.org Kernel Setup

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: KERNEL_BUILD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Attempt NeBuild
      run: sudo curl https://git.src.nekernel.org/nebuild/releases/download/v0.0.6-apple-m1/nebuild-debian -o /usr/bin/nebuild && sudo chmod +x /usr/bin/nebuild
    - name: Check NeBuild
      run: nebuild -v
    - name: Attempt Kernel Setup
      run: mkdir tmp && git clone https://git.src.nekernel.org/kernel.git tmp/kernel && sudo ./tmp/kernel/scripts/setup_x64_project.sh
      