name: Ne.app Build [SANITY]

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: SYS_BUILD_SANITY

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Attempt NeBuild
      run: sudo curl https://github.com/ne-foss/bld/releases/download/v0.0.6-apple-m1/ne-build-debian -o sanity-test
